### ISSUE TITLE
CSS常见问题解决方案

### ISSUE THREAD

**Issue by Darren-supreme** [Darren-supreme/CV#3]
### img标签间隔空白问题

1. 所在标签父容器设置font-size
```css
font-size:0
```
2. img设置display
```css
img{
    display"block;
}
```
```css
3.img设置vertical-align
img{
    vertical-align:bottom;//top middle均可
}
```
